name: 'Create .pdf file'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  pull-requests: read
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  list_markdown:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: create file list
        id: files_list
        run: |
          echo "files=$(printf '"%s" ' *.markdown)" > $GITHUB_OUTPUT
    outputs:
      files: ${{ steps.files_list.outputs.files }}
  make-pdfs:
    needs: list_markdown
    if: ${{ always() }}
    strategy:
      matrix:
        file: ${{ needs.list_markdown.outputs.files }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: create file list
        id: files_list
        run: |
          echo "files=$(printf '"%s" ' *.markdown)" > $GITHUB_OUTPUT

      - name: Build slides .pdf
        uses: docker://pandoc/latex:3.2
        with:
          args: --defaults=settings.yaml -o ${{matrix.file}}-slides.pdf ${{matrix.file}}

      - name: Build handouts .pdf
        uses: docker://pandoc/latex:3.2
        with:
          args: --defaults=settings.yaml -V handout -o ${{matrix.file}}-handouts.pdf ${{matrix.file}}

      - name: Build notes .pdf
        uses: docker://pandoc/latex:3.2
        with:
          args: --defaults=settings.yaml --metadata=beameroption="show only notes" -o ${{matrix.file}}-notes.pdf ${{matrix.file}}

      - name: Upload .pdf
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Upload from GitHub Actions
